dice_range_from: 0.8
dice_range_to: 0.95
expand_size_from: 100
expand_size_step: 50
expand_size_to: 150
iteration_from: 15
iteration_step: 5
iteration_to: 15
kernel_size_from: 6
kernel_size_step: 3
kernel_size_to: 9
mask_num: 5
patch_size_from: 20
patch_size_step: 5
patch_size_to: 20
probability_from: 0.7
probability_step: 0.1
probability_to: 0.8
